# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c96a98281a7a4b2ab552718e8787bfacb6e4ade648242ced37d371af904fd08e5fa326bb2529934f8b0a1acbdbea16fd4d07c4693ced182a653317bfc56e92e

test:
  secret_key_base: 79b427023292283ea82edee05fc543d891438d94c0e99bb4ffd262fd6bacec7410391cc1c21510a7ceed026cd80c3ea45212efac52c9343fbd1e3299e2f3bcb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
